services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    build:
      context: ./src-nginx
      args:
        url_docker: ${url_docker_index}
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - SHARED_DATA_DIR=${SHARED_DATA_DIR}
      - NGINX_LOG_FOLDER=${SHARED_LOGS_DIR}/nginx/
      - NGINX_STATIC_FOLDER=${SHARED_DATA_DIR}/www/static/
      - NGINX_MEDIA_FOLDER=${SHARED_DATA_DIR}/www/media/
      - NGINX_PORT_HTTP=${NGINX_PORT_HTTP}
      - NGINX_PORT_HTTPS=${NGINX_PORT_HTTPS}
      - DJANGO_PORT=${DJANGO_PORT}
    ports:
      - "${NGINX_PORT_HTTP}:${NGINX_PORT_HTTP}"
      - "${NGINX_PORT_HTTPS}:${NGINX_PORT_HTTPS}"
    volumes:
      - ./src-nginx/templates:/etc/nginx/templates
      - datashare:${SHARED_DATA_DIR}
      - applogs:${SHARED_LOGS_DIR}
      - cache_nginx:/var/cache/nginx
    networks:
      - appnet

  mgdb:
    container_name: ${PROJECT_NAME}_mgdb
    restart: unless-stopped
    build:
      context: ./src-mgdb
      args:
        url_docker: ${url_docker_index}
    env_file:
      - ./src-mgdb/.env
    command:
      [
        "--bind_ip",
        "0.0.0.0",
        "--port",
        "${MGDB_PORT}",
        "--quiet",
        "--wiredTigerCacheSizeGB",
        "3.5",
      ]
    ports:
      - "${MGDB_PORT}:${MGDB_PORT}"
    volumes:
      - dbdata_mgdb:/data/db
      - ./src-mgdb/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - appnet
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 8G
        reservations:
          memory: 2G

  valkey:
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_valkey
    env_file:
      - ./src-valkey/.env
    build:
      context: ./src-valkey
      args:
        url_docker: ${url_docker_index}
        port_valkey: ${VALKEY_PORT}
    # Enable persistance:
    # --save: save DB snapshot if <keys: 1> change in <seconds: 60>
    # --dir /data: saves data to mountpoint
    command: valkey-server --save 60 1 --loglevel warning --dir /data
    # ports:
    #   - "${VALKEY_PORT}:${VALKEY_PORT}"
    volumes:
      - dbdata_valkey:/data
    networks:
      - appnet

  django:
    container_name: ${PROJECT_NAME}_django
    restart: unless-stopped
    env_file:
      - ./src-django/.env
    build:
      context: ./src-django
      args:
        url_pypi: ${url_pypi_index}
        url_docker: ${url_docker_index}
    volumes:
      ## Maps host dir, mount into to container vol
      - datashare:/datashare
      - applogs:/applogs
    networks:
      - appnet
    entrypoint:
      - bash
      - entrypoint-gunicorn.sh
      - ${DJANGO_PORT}

  worker:
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_worker
    build:
      context: ./src-django
      args:
        url_pypi: ${url_pypi_index}
        url_docker: ${url_docker_index}
    env_file:
      - ./src-django/.env
    volumes:
      - datashare:/datashare
      - applogs:/applogs
    entrypoint:
      - bash
      - entrypoint-celery.sh
    networks:
      - appnet

volumes:
  datashare:
  applogs:
  dbdata_mgdb:
  dbdata_valkey:
  cache_nginx:

networks:
  appnet:
